# FW1 - System settings (Section 3)
# FortiGate-VM, FortiOS 7.0.9

config system global
    set admintimeout 480
    set hostname "FW1"
    set timezone 65
end

config system dns
    set primary 8.8.8.8
    set secondary 1.1.1.1
end

config system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "192.168.100.230"
        next
    end
    set server-mode enable
    set interface "port5"
end
